### ISSUE TITLE
Last edited bug

### ISSUE THREAD

**Issue by JakubKosmaty** [pichalite/nodebb-theme-material#82] opened 2018-05-01 10:45 UTC
![shu_pqmjv8](https://user-images.githubusercontent.com/20679265/39470326-57117508-4d3d-11e8-9d0c-a7ac00ef07f4.png)

**Comment by pichalite** [comment] 2018-05-02 04:01
Duplicate of #61

**Closed as completed by pichalite** 2018-05-02 04:01 UTC
